spring:
  application:
    name: 'transaction-service'
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: ${KAFKA_ACKS:all}
      retries: ${KAFKA_RETRIES:2147483647}
      properties:
        enable.idempotence: ${KAFKA_ENABLE_IDEMPOTENCE:true}
        linger.ms: ${KAFKA_LINGER_MS:5}
        delivery.timeout.ms: ${KAFKA_DELIVERY_TIMEOUT:120000}
        spring.json.add.type.headers: false

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${KAFKA_CONSUMER_GROUP_ID:account-service-group}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/transaction_db}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

server:
  port: ${PORT:5001}

transaction:
  kafka:
    topics:
      accounts:
        name: ${KAFKA_TOPIC_ACCOUNT:balance-v1}
        partitions: ${KAFKA_TOPIC_PARTITIONS:1}
        replicas: ${KAFKA_TOPIC_REPLICAS:1}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
