version: '3.8'

services:
  # --- Banco do Account Service (Porta 5432) ---
  postgres-account:
    image: postgres:15-alpine
    container_name: itau_postgres_account
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: account_db
    ports:
      - "5432:5432" # Porta padrão
    volumes:
      - pg_account_data:/var/lib/postgresql/data
    networks:
      - itau-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d account_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Banco do Ledger Service (Porta 5433) ---
  postgres-ledger:
    image: postgres:15-alpine
    container_name: itau_postgres_ledger
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: ledger_db
    ports:
      - "5433:5432" # <--- AQUI: No seu PC será localhost:5433
    volumes:
      - pg_ledger_data:/var/lib/postgresql/data
    networks:
      - itau-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ledger_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Infra Kafka ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: itau_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - itau-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: itau_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - itau-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: itau_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8090:8080" # <--- MUDEI PARA 8090 (Veja o aviso abaixo)
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - itau-network

volumes:
  pg_account_data:
  pg_ledger_data:

networks:
  itau-network:
    driver: bridge